POST http://localhost:5000/
Content-Type: application/json

{
    "artName": "Painting_1",
    "serial": 1,
    "src": "https://images.metmuseum.org/CRDImages/ep/original/DT1946.jpg",
    "alt": "Image1",
    "bids": [
        {
            "user": "User1",
            "bid": 100
        }
    ]
}

###
POST http://localhost:5000/
Content-Type: application/json

{
    "artName": "Painting_2",
    "serial": 2,
    "src": "https://images.metmuseum.org/CRDImages/ep/original/DT1946.jpg",
    "alt": "Image2  ",
    "bids": [
        {
            "user": "User2",
            "bid": 100
        }
    ]
}

### 

GET http://localhost:5000/662177550db8f553f2fdf49f

###

GET http://localhost:5000/

###

PUT http://localhost:5000/662177550db8f553f2fdf49f
Content-Type: application/json

{
    "artName": "Testing Update Function",
    "serial": 124,
    "bids": [
        {
            "user": "User1",
            "bid": 120
        },
        {
            "user": "User3",
            "bid": 200
        }
    ]
}

###

DELETE http://localhost:5000/662177550db8f553f2fdf49f
